language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update
  - composer dump-autoload -o

script: vendor/bin/phpunit

notifications:
  email:
    - dave@opulencephp.com

sudo: false

matrix:
  fast_finish: true
